version: '3.6'

services:
  php:
    ports:
      - '8080:80'
  database:
    environment:
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
  adminer:
    ports:
      - '8081:8080' # 8081 : port sur navigateur / 8080 : port sur lequel tourne le service