version: 2
jobs:
  build:
    docker:
      - image: chialab/php-dev:7.2-apache

    steps:
      - checkout

      - run:
          name: Install vendor
          command: composer install

      - run:
          name: Code Style
          command: make test